### PR TITLE
Adds casks

### PR DESCRIPTION
**Pull request by ksatirli**
Initial PR for all currently released `6.x.x` versions of VirualBox

# Added Cask(s)

- `virtualbox@6.0.0-beta1`
- `virtualbox@6.0.0-beta2`
- `virtualbox@6.0.0-beta3`
- `virtualbox@6.0.0-rc1`
- `virtualbox@6.0.0`
- `virtualbox@6.0.2`
- `virtualbox@6.0.4`
- `virtualbox@6.0.6`
- `virtualbox@6.0.8`
- `virtualbox@6.0.10`
- `virtualbox@6.0.12`
- `virtualbox@6.0.14`
- `virtualbox@6.0.16`
- `virtualbox@6.0.18`

- `virtualbox@6.1.0-beta1`
- `virtualbox@6.1.0-beta2`
- `virtualbox@6.1.0-rc1`
- `virtualbox@6.1.0`
- `virtualbox@6.1.2`
- `virtualbox@6.1.4`

Any other relevant environment information:

Running the `generate-casks.sh` and `verify-casks.sh` scripts is only possible if you have checked out `operatehappy/homebrew-tools` 

# TODO

- [X] Checked open [Pull Requests](https://github.com/operatehappy/homebrew-virtualbox/pulls) for a similar Cask update
- [X] Built the Cask locally and verified its installability
- [X] Tested installability using `brew cask install product@x.y.z.rb`
- [X] Tested uninstallability using `brew cask uninstall product@x.y.z.rb`
- [X] Audited the Cask using `brew cask audit --download product@x.y.z` with no errors
- [X] Style-checked the Cask using `brew cask style --fix product@x.y.z` and reported no offenses

### CODE REVIEW

**Review by bbaassssiiee — APPROVED** [review]
LFTM

**Comment by bbaassssiiee** [comment]
There is a code quality test failing

**Comment by ksatirli** [comment]
> There is a code quality test failing

Yeah; that's because some files from https://github.com/operatehappy/homebrew-tools/pull/1 aren't merged yet and the code quality check actually checks those files out to validate the tools in this repository.

Once that PR is merged, this should start working a lot better :)

**Comment by ksatirli** [comment]
> There is a code quality test failing

This has been resolved as the upstream PR has been merged, all checks are now passing.

**Pull request merged**
